### ISSUE TITLE
AiMode Loader

### ISSUE THREAD

**Issue by Verclene** [Legojer/LittleMaidMobEnhanced#1]
There seems to be no class which loades extra aimode classes. But LMMX has, so if I put only additional aimode classes other than LMMX in the mods folder, they are loaded to LMMX automatically and I can use them.
On LMMEnhanced, must add-on developers register aimode classes to ModeManager#maidModeList manually?

**Comment by Goujer** [comment]
I wasn't aware of this functionality in any version of the mod, but upon inspecting the other versions it would indeed appear that you could load new aimodes from the mods folder. LMME's original fork never had any add-on functionality to begin with, I'm trying to get it back but it has been difficult so far.

As of right now if someone wanted to add a new aimode to the mod they would have to add the new aimode class to ModeManager.maidModeList manually. I'll get to work on this as soon as I can get LMME to load new models and textures.

**Comment by Goujer** [comment]
Hey, do you know if there is an add-on that has an aimode class that I could use for testing?

Edit: I changed things up so it should load new aimodes like NX, but I still have no way to test if it works.

**Comment by Verclene** [comment]
How about the 'Sugar Hunter' in [EntityModeSugarBiome](http://forum.minecraftuser.jp/viewtopic.php?t=10418) for testing? This mode enables maids to harvest sugar canes.
*This add-on is based on LMMX, so need transforming. The package includes sources.

**Comment by Goujer** [comment]
Thanks I will try this out as soon as possible.

**Comment by Goujer** [comment]
Finally I have confirmed that AI Modes load and I have added support for at least that that sugar biome one.
